---
galaxy_info:
  author: Scott Jeter
  description: Install Kubernetes tools (kubectl, helm, k3sup)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
