---
container_tools:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - podman
  - podman-compose
  - buildah
  - skopeo

ansible_user: "devops"