---
galaxy_info:
  author: your_name
  description: Completely remove Docker and related components
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
