---
- name: Install dnf plugins core for Docker repository
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker CE repository
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg
    file: docker-ce

- name: Install container tools
  become: true
  ansible.builtin.dnf:
    name: "{{ container_tools }}"
    state: present
    update_cache: true

- name: Create docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

# nftables is required for Docker networking on Fedora 37 and later
- name: Install nftables for Docker networking
  become: true
  ansible.builtin.dnf:
    name:
      - nftables
    state: present

- name: Start and enable nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true

- name: Create Docker config directory
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker to use nftables
  become: true
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "iptables": false,
        "ip6tables": false
      }
    mode: '0644'

# starting Docker service and socket
- name: Start and enable Docker service
  become: true
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    daemon_reload: true

- name: Start and enable Docker socket
  become: true
  ansible.builtin.systemd:
    name: docker.socket
    state: started
    enabled: true

# Wait for Docker to be ready
- name: Wait for Docker to be ready
  become: true
  ansible.builtin.command: docker version
  register: docker_version
  retries: 5
  delay: 3
  until: docker_version.rc == 0
  changed_when: false

- name: Display Docker version
  ansible.builtin.debug:
    var: docker_version.stdout_lines

- name: Test Docker with hello-world
  become: true
  ansible.builtin.command: docker run --rm hello-world
  register: docker_test
  changed_when: false

- name: Display Docker test result
  ansible.builtin.debug:
    msg: "Docker is working correctly!"
  when: docker_test.rc == 0

- name: Configure SELinux for containers and web services
  become: true
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - container_manage_cgroup
    - container_use_cephfs
    - container_use_devices
    - httpd_can_network_connect
    - virt_sandbox_use_all_caps
  ignore_errors: true
